# Generated by Django 3.2.13 on 2022-05-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='user_role',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
